### ISSUE TITLE
Can't toggle todo in Android in companion app

### ISSUE THREAD

**Issue by realdimik** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#27]
following code works well in PC, but in Android in companion app the button will show only sun1, not todo1 :(

```
      - title: Click test
        type: entities
        entities:
          - action_name: Toggle
            icon: mdi:power
            name: Sun1
            tap_action:
              action: fire-dom-event
              local_conditional_card:
                action: toggle
                ids:
                  - todo1
                  - sun1
            type: button
      - type: custom:local-conditional-card
        default: show
        id: sun1
        card:
          entities:
            - sun.sun
          title: Sun 1
          type: entities
        persist_state: true
      - type: custom:local-conditional-card
        default: show
        id: todo1
        card:
          type: todo-list
          entity: todo.shopping_list
        persist_state: false

```
