### ISSUE TITLE
Multi_call

### ISSUE THREAD

**Issue by pex81** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#36]
Hi, is it possible to make a call to your card via hass.callService?
for example
```
- type: custom:button-card
  entity: input_boolean.test
  show_icon: false
  show_name: false
  tap_action:
    action: custom
    multi_calls: |
      [[[ 
        hass.callService('homeassistant.toggle', 'input_boolean.test');
        
        hass.callService('fire-dom-event', '', {
          event_type: 'local_conditional_card',
          event_data: {
            action: 'toggle',
            ids: ['tab1', 'tab2']
          }
        });
      ]]]  
```

**Comment by PiotrMachowski** [comment]
`fire-dom-event` is handled on the browser side, so it can't be used in the service call.
This code might work instead:
```js
cardEvent = new Event('ll-custom', { bubbles: true, cancelable: false, composed: true});
cardEvent.detail = {
  "local_conditional_card": {
    "action": "toggle",
    "ids": ["sun1"]
  }
};
document.dispatchEvent(cardEvent);
```

By the way, where does this config come from?
```yaml
  tap_action:
    action: custom
    multi_calls: |
      ...
```

**Comment by pex81** [comment]
> `fire-dom-event` is handled on the browser side, so it can't be used in the service call. This code might work instead:
> 
> cardEvent = new Event('ll-custom', { bubbles: true, cancelable: false, composed: true});
> cardEvent.detail = {
>   "local_conditional_card": {
>     "action": "toggle",
>     "ids": ["sun1"]
>   }
> };
> document.dispatchEvent(cardEvent);
> 
> By the way, where does this config come from?
> 
>   tap_action:
>     action: custom
>     multi_calls: |
>       ...

Hi, thanks for the reply, I will try as you suggest.
For multi_calls: I found information on custom:button-card [github](https://github.com/custom-cards/button-card/issues?q=is%3Aissue%20state%3Aopen%20multi_calls)

**Comment by PiotrMachowski** [comment]
> For multi_calls: I found information on custom:button-card [github](https://github.com/custom-cards/button-card/issues?q=is%3Aissue%20state%3Aopen%20multi_calls)

It is weird, I have never seen it.

Anyway, this version works:

```yaml
    - type: custom:button-card
      entity: input_boolean.test
      show_icon: false
      show_name: false
      tap_action:
        action: custom
        multi_calls: |
          [[[ 

          const cardEvent = new Event('ll-custom', { bubbles: true, cancelable:
          false, composed: true});

          cardEvent.detail = {
            "local_conditional_card": {
              "action": "toggle",
              "ids": ["tab1", "tab2"]
            }
          };

          document.dispatchEvent(cardEvent);

          ]]] 
```
