### ISSUE TITLE
Some custom child cards issue

### ISSUE THREAD

**Issue by estevez-dev** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#4]
First of all, thanks for such a useful card.

I found an issue using `custom:local-conditional-card` when its child `card` is set to some custom lovelace card. The card is not displayed at all:
```yaml
type: 'custom:local-conditional-card'
default: show
id: living_room_2
card:
  type: 'custom:mini-media-player'
  entity: media_player.living_room_media
```
Media player card itself is working properly:
```yaml
type: 'custom:mini-media-player'
entity: media_player.living_room_media
```
![screenshot-homeassistant_8123-2021 02 16-17_18_19](https://user-images.githubusercontent.com/1819786/108082721-0f9a7080-707b-11eb-84fb-68beebba7081.png)

It is also doesn't work with `custom:simple-thermostat`, but works with `custom:button-card`.
