### ISSUE TITLE
Error: expected str instance, Optional found

### ISSUE THREAD

**Issue by alexanderphoenix** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#8]
Hi @PiotrMachowski 

After installing this extension I've been getting the following error:
```
Failed to call service light/turn_on. sequence item 0: expected str instance, Optional found
```

I didn't realise at first it could've been the `local-conditional-card` and posted this problem on the home assistant community forum:
https://community.home-assistant.io/t/error-expected-str-instance-optional-found/305019

Would you be able to have a look please? I'm curious to have your thoughts on this.

Cheers

**Comment by PiotrMachowski** [comment]
Hi @alexanderphoenix!

I think that it can be caused by this card, for now it should work with this change in your config:
```
type: button
tap_action:
  action: call-service
  service: light.turn_on
  service_data:
    entity_id: light.master_bedroom_lamp
    brightness_pct: 10
show_name: false
icon: 'mdi:lightbulb-outline'
```
Can you confirm if this solves your problem?
