### ISSUE TITLE
Doesn't work on "custom:button-card"

### ISSUE THREAD

**Issue by shlomki** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#9]
Hi, this is an awesome card you've made here! thanks for all the work!

I've noticed that when I use "custom:button-card", it doesn't work (the card is displayed but I can't hide it).
However if I wrap it with vertical-stack, it works just fine.

Example that **doesn't work**:
```
type: custom:local-conditional-card
default: show
id: light
card:
  type: custom:button-card
  name: Light
```

Example that **works**:
```
type: custom:local-conditional-card
default: show
id: light
card:
  type: vertical-stack
  cards:
    - type: custom:button-card
      name: Light

```

I don't see any errors in the console.
I've noticed that for some reason, `hui-button-card-card` doesn't get created (it stays as `button-card`)
but `hui-vertical-stack-card` does get created in the DOM. Perhaps that's the problem?
